version: '3.9'

networks:
  news24:
    driver: bridge

services:
  mysql57:
    image: mysql:5.7
    container_name: news24_epaper_db
    networks:
      - news24
    environment:
      MYSQL_ROOT_PASSWORD: droid273
      MYSQL_DATABASE: mrnetdoptor_epaper2
      MYSQL_USER: mrnetdoptor_epaper2
      MYSQL_PASSWORD: droid273
    volumes:
      - ~/.docker/epaper_mysql57:/var/lib/mysql
      - ./epaper/:/docker-entrypoint-initdb.d
  
  mysql80:
    image: mysql:8.0
    container_name: news24_db
    networks:
      - news24
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: droid273
      MYSQL_DATABASE: news
      MYSQL_USER: news
      MYSQL_PASSWORD: droid273
    volumes:
      - ~/.docker/epaper_mysql80:/var/lib/mysql
      - ./admin/database/:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    networks:
      - news24
    environment:
      PMA_HOST: mysql57,mysql80
      MYSQL_ROOT_PASSWORD: droid273
    depends_on:
      - mysql57
      - mysql80
  
  nginx:
    image: nginx:latest
    container_name: server
    networks:
      - news24
    ports:
      - "80:80"
      - "81:81"
      - "90:90"
    volumes:
      - ~/.docker/news24/var_log_nginx:/var/log/nginx/
      - ./admin/:/var/www/html/admin/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - admin
      - news
  news:
    image: node:20 # Use a Node.js 18 image as the base
    container_name: news24
    networks:
      - news24
    working_dir: /usr/src/app
    volumes:
      - ./frontend/:/usr/src/app # Mount the project directory
      - /usr/src/app/node_modules # Prevent node_modules overwrite
    environment:
      NODE_ENV: development
    command: sh -c "npm install && npm run dev -- -p 3000"
    depends_on:
      - admin
  
  admin:
    build:
      context: ./admin/docker/8.3/
      dockerfile: Dockerfile
    container_name: news24_admin
    networks:
      - news24
    volumes:
      - ./admin/:/var/www/html
    working_dir: /var/www/html/
    command: bash -c "composer update && php-fpm"
    depends_on:
      - mysql80
  
  epaper:
    build:
      context: ./epaper/docker/
      dockerfile: Dockerfile
    container_name: news24_epaper
    networks:
      - news24
    volumes:
      - ./epaper/:/var/www/html
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
    working_dir: /var/www/html/
    #command: bash -c "php ./project/composer.phar update"
    command: apache2-foreground
    depends_on:
      - mysql57


