version: '3.9'

networks:
  news24:
    driver: bridge

services:
  mysql57:
    image: mysql:5.7
    container_name: news24_epaper_db
    networks:
      - news24
    ports:
      - "3307:3306" #epaper
    environment:
      MYSQL_ROOT_PASSWORD: droid273
      MYSQL_DATABASE: epaper
      MYSQL_USER: news
      MYSQL_PASSWORD: droid273
    volumes:
      - /home/${USER}/.docker/news24/epaper_mysql57:/var/lib/mysql
      - ./epaper/:/docker-entrypoint-initdb.d
  
  mysql80:
    image: mysql:8.0
    container_name: news24_db
    networks:
      - news24
    ports:
      - "3306:3306"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: droid273
      MYSQL_DATABASE: news
      MYSQL_USER: news
      MYSQL_PASSWORD: droid273
    volumes:
      - /home/${USER}/.docker/news24/epaper_mysql80:/var/lib/mysql
      - ./admin/database/:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    networks:
      - news24
    environment:
      MYSQL_ROOT_PASSWORD: droid273
    depends_on:
      - mysql80
      - mysql57
    volumes:
    - ./phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
  
  nginx:
    image: nginx:latest
    container_name: nginx
    networks:
      - news24
    ports:
      - "80:80" #epaper
      - "81:81" #news
      - "8000:8000" #admin
      - "3300:3300" #pma
    volumes:
      - ./admin/:/var/www/html/admin/
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - phpmyadmin
      - admin
      - news
      - epaper
  news:
    image: node:20
    container_name: news24
    networks:
      - news24
    working_dir: /usr/src/app
    volumes:
      - ./frontend/:/usr/src/app
    environment:
      NODE_ENV: development
    command: sh -c "npm run dev -- -p 3000 --hostname news"
    depends_on:
      - admin
  
  admin:
    build:
      context: ./admin/docker/8.3/
      dockerfile: Dockerfile
    container_name: news24_admin
    networks:
      - news24
    volumes:
      - ./admin/:/var/www/html/
    working_dir: /var/www/html/
    #command: bash -c "composer install --no-dev --optimize-autoloader && chmod -R 777 /var/www/html/storage /var/www/html/bootstrap/cache && php-fpm"
    command: "php-fpm"
    depends_on:
      - mysql80
  
  epaper:
    build:
      context: ./epaper/docker/
      dockerfile: Dockerfile
    container_name: news24_epaper
    networks:
      - news24
    volumes:
      - ./epaper/:/var/www/html
      - ./epaper/php.ini:/usr/local/etc/php/php.ini
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
      - DB_HOST=mysql57
      - DB_PORT=3306
    working_dir: /var/www/html/
    #command: bash -c "php ./project/composer.phar update"
    command: apache2-foreground
    depends_on:
      - mysql57


